import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import type { Skill } from '../src/skills/store.js';
import type { SpecFlow, SpecSegment, SpecStep } from '../src/spec/ir.js';
import { LiftError, isOwnedFlowFile, liftFlowFile } from '../src/spec/lift.js';
import { FINGERPRINT_DIMS } from '../src/execution/fingerprint.js';

// --- test-local builder for the emit.ts layout (contract section 3) -------
//
// emit.ts is being written concurrently by another agent, so lift's own
// tests cannot depend on it for the primary round-trip check. This helper
// reproduces only what liftFlowFile actually reads: the header comment, the
// begin/end region markers, and `export const FLOW = <json>;` inside them.
// It deliberately omits the rest of the generated file (Vars/Outputs types,
// steps object, runFlow) since lift never looks at that TypeScript body.
function buildFlowFileText(
  spec: SpecFlow,
  opts: { omitBegin?: boolean; omitEnd?: boolean; header?: boolean; handEditedJson?: string } = {},
): string {
  const { omitBegin, omitEnd, header = true, handEditedJson } = opts;
  const lines: string[] = [];
  if (header) {
    lines.push('// @sitelooper-flow v1');
    lines.push(`// Generated by sitelooper from flow "${spec.name}" — do not edit by hand.`);
    lines.push('// Repair drift with `sitelooper repair <this file>`; the FLOW constant below is the source of truth.');
  }
  lines.push("import { expect, type Page } from '@playwright/test';");
  lines.push('');
  if (!omitBegin) lines.push('// @sitelooper-flow-begin');
  const json = handEditedJson ?? JSON.stringify(spec, null, 2);
  lines.push(`export const FLOW = ${json};`);
  if (!omitEnd) lines.push('// @sitelooper-flow-end');
  lines.push('');
  lines.push(`export type Vars = { ${spec.vars.map((v) => `${v}: string`).join(', ')} };`);
  lines.push('export interface Outputs { [key: string]: string }');
  lines.push('');
  lines.push('export const steps = {};');
  lines.push('');
  lines.push('export async function runFlow(page: Page, vars: Vars): Promise<Outputs> {');
  lines.push('  const outputs: Outputs = {};');
  lines.push(`  await page.goto(${JSON.stringify(spec.startUrl)});`);
  lines.push('  return outputs;');
  lines.push('}');
  return lines.join('\n');
}

// --- hand-built fixtures ----------------------------------------------------

function segment(id: string, extra: Partial<SpecSegment> = {}): SpecSegment {
  return {
    id,
    template: `do the ${id} thing with {{v1}}`,
    params: { v1: { example: 'foo', usedIn: [1] } },
    preconditions: { urlPattern: 'http://localhost:5173/x' },
    steps: [
      {
        tool: 'click',
        args: { target: '{{v1}}' },
        locators: { target: [{ kind: 'role', role: 'button', name: '{{v1}}', seen: 1 } as any] },
      },
      {
        tool: 'loop',
        args: {},
        locators: {},
        while: [{ kind: 'css', selector: '.row', seen: 1 } as any],
        max: 10,
        body: [
          {
            tool: 'click',
            args: { target: 'Delete' },
            locators: { target: [{ kind: 'text', text: 'Delete', seen: 1 } as any] },
          },
        ],
      },
    ],
    ...extra,
  };
}

function step(id: string, extra: Partial<SpecStep> = {}): SpecStep {
  return {
    id,
    instruction: `Step ${id}`,
    params: { v1: 'literal', v2: '{{someVar}}', v3: '{{01-open.title}}' },
    outputs: ['title'],
    segments: [segment(`${id}-seg`)],
    ...extra,
  };
}

const HAND_BUILT_FLOWS: SpecFlow[] = [
  // minimal: one step, no segments (no converged procedure)
  {
    version: 1,
    name: 'minimal',
    origin: 'http://localhost:5173',
    startUrl: 'http://localhost:5173/',
    vars: [],
    steps: [step('01-open', { segments: [] })],
  },
  // multi-step, multi-segment, with loops/mints/derived
  {
    version: 1,
    name: 'full',
    origin: 'http://localhost:5173',
    startUrl: 'http://localhost:5173/project-manager',
    vars: ['name', 'client'],
    steps: [
      step('01-open', { params: {}, outputs: [] }),
      step('02-create', {
        params: { v1: '{{name}}', v2: '{{client}}' },
        outputs: ['id', 'url'],
        segments: [
          segment('02-create-seg', {
            derived: { d1: { step: 2, at: 'id', example: '42' } },
          }),
        ],
      }),
    ],
  },
  // no steps at all
  {
    version: 1,
    name: 'empty',
    origin: 'http://localhost:5173',
    startUrl: 'http://localhost:5173/',
    vars: [],
    steps: [],
  },
];

function wrapSkillAsFlow(skill: Skill): SpecFlow {
  const derived = skill.derived;
  const segments: SpecSegment[] =
    skill.seq == null || skill.seq.index === 0
      ? [
          {
            id: skill.id,
            template: skill.template,
            params: skill.params,
            preconditions: skill.preconditions.requireText
              ? { urlPattern: skill.preconditions.urlPattern, requireText: skill.preconditions.requireText }
              : { urlPattern: skill.preconditions.urlPattern },
            steps: skill.steps,
            ...(derived ? { derived } : {}),
          },
        ]
      : [];
  return {
    version: 1,
    name: `skill-${skill.id}`,
    origin: skill.origin,
    startUrl: skill.preconditions.urlPattern,
    vars: Object.keys(skill.params),
    steps: [
      {
        id: '01-run',
        instruction: skill.template,
        params: Object.fromEntries(Object.keys(skill.params).map((k) => [k, `{{${k}}}`])),
        outputs: [],
        segments,
      },
    ],
  };
}

const FWAT2_SKILLS_PATH = path.join(__dirname, '..', 'bench', 'results-published', 'fwat2-skills', 'localhost_5173.json');
const fwat2Skills: Skill[] = JSON.parse(fs.readFileSync(FWAT2_SKILLS_PATH, 'utf8'));

describe('liftFlowFile: round trip (test-local emitter layout)', () => {
  it.each(HAND_BUILT_FLOWS.map((spec) => [spec.name, spec] as const))('hand-built spec "%s"', (_name, spec) => {
    const text = buildFlowFileText(spec);
    const { spec: lifted, version } = liftFlowFile(text);
    expect(version).toBe(1);
    expect(lifted).toEqual(spec);
  });

  it('round-trips every skill in the fwat2 store, wrapped as a one-step flow', () => {
    expect(fwat2Skills.length).toBeGreaterThan(0);
    for (const skill of fwat2Skills) {
      const spec = wrapSkillAsFlow(skill);
      const text = buildFlowFileText(spec);
      const { spec: lifted } = liftFlowFile(text);
      expect(lifted).toEqual(spec);
    }
  });
});

describe('liftFlowFile: round trip through the real emitter (when present)', () => {
  it('emitFlowFile → liftFlowFile round-trips, or is skipped if emit.ts is absent', async () => {
    let emitFlowFile: undefined | ((spec: SpecFlow, o: { tier: 'plain' }) => { source: string; warnings: string[] });
    try {
      const mod: any = await import('../src/spec/emit.js');
      emitFlowFile = mod.emitFlowFile;
    } catch {
      emitFlowFile = undefined;
    }
    if (typeof emitFlowFile !== 'function') {
      // emit.ts not landed yet (or doesn't export emitFlowFile) — nothing to test.
      return;
    }
    for (const spec of HAND_BUILT_FLOWS) {
      const { source } = emitFlowFile(spec, { tier: 'plain' });
      const { spec: lifted } = liftFlowFile(source);
      expect(lifted).toEqual(spec);
    }
  });
});

describe('isOwnedFlowFile', () => {
  it('is true for a well-formed emitted file', () => {
    expect(isOwnedFlowFile(buildFlowFileText(HAND_BUILT_FLOWS[0]))).toBe(true);
  });
  it('is false when the header comment is missing', () => {
    expect(isOwnedFlowFile(buildFlowFileText(HAND_BUILT_FLOWS[0], { header: false }))).toBe(false);
  });
  it('is false for an arbitrary file', () => {
    expect(isOwnedFlowFile('export const x = 1;')).toBe(false);
  });
});

describe('liftFlowFile: negative cases (hand-edited files)', () => {
  it('throws LiftError when the begin marker is missing', () => {
    const text = buildFlowFileText(HAND_BUILT_FLOWS[0], { omitBegin: true });
    expect(() => liftFlowFile(text)).toThrow(LiftError);
    expect(() => liftFlowFile(text)).toThrow(/begin/i);
  });

  it('throws LiftError when the end marker is missing', () => {
    const text = buildFlowFileText(HAND_BUILT_FLOWS[0], { omitEnd: true });
    expect(() => liftFlowFile(text)).toThrow(LiftError);
    expect(() => liftFlowFile(text)).toThrow(/end/i);
  });

  it('throws LiftError with a JSON-parse reason on a trailing comma (hand-edited FLOW)', () => {
    const spec = HAND_BUILT_FLOWS[0];
    // Simulate a human editing the emitted JSON literal directly: a trailing
    // comma after the last property, which JSON (unlike JS) rejects.
    const handEditedJson = JSON.stringify(spec, null, 2).replace(/\n\}$/, ',\n}');
    const text = buildFlowFileText(spec, { handEditedJson });
    expect(() => liftFlowFile(text)).toThrow(LiftError);
    expect(() => liftFlowFile(text)).toThrow(/JSON/i);
  });

  it('throws LiftError on an unsupported version', () => {
    const spec3 = { ...HAND_BUILT_FLOWS[0], version: 3 } as unknown as SpecFlow;
    const text = buildFlowFileText(spec3);
    expect(() => liftFlowFile(text)).toThrow(LiftError);
    expect(() => liftFlowFile(text)).toThrow(/version/i);
  });

  /**
   * notes/ROBUSTNESS.md finding 5: a step's frame path, page index and page effect
   * travel in FLOW verbatim (a version-2 spec), and a malformed one is refused
   * naming the field — the artifact acts on all three.
   */
  describe('frame and page context', () => {
    const framed = (extra: Record<string, unknown>): SpecFlow => {
      const spec = structuredClone(HAND_BUILT_FLOWS[1]) as SpecFlow;
      spec.version = 2;
      Object.assign(spec.steps[0].segments[0].steps[0], extra);
      return spec;
    };
    const context = {
      contexts: { target: { frame: [{ selectors: ['iframe[title="Payment"]', 'iframe[src*="/frames/inner"]'], title: 'Payment' }] } },
      page: 1,
      effect: { kind: 'popup', urlPattern: 'http://127.0.0.1/popup/child' },
    };

    it('round-trips contexts, page and effect on a version-2 spec', () => {
      const spec = framed(context);
      const { spec: lifted, version } = liftFlowFile(buildFlowFileText(spec));
      expect(version).toBe(2);
      expect(lifted).toEqual(spec);
      expect(lifted.steps[0].segments[0].steps[0]).toMatchObject(context);
    });

    it.each([
      ['a frame hop with no selectors', { contexts: { target: { frame: [{ selectors: [] }] } } }, /contexts\.target\.frame"\[0\]: "selectors"/],
      ['a frame that is not an array', { contexts: { target: { frame: 'iframe' } } }, /"contexts\.target\.frame" must be an array/],
      ['a context for an unknown key', { contexts: { other: { frame: [] } } }, /may only name target and source/],
      ['a negative page', { page: -1 }, /"page" must be a non-negative integer/],
      ['an unknown effect', { effect: { kind: 'teleport' } }, /"effect\.kind" must be one of/],
      ['a switch with no index', { effect: { kind: 'switch' } }, /"effect\.to"/],
    ])('refuses %s', (_name, extra, message) => {
      const text = buildFlowFileText(framed(extra));
      expect(() => liftFlowFile(text)).toThrow(LiftError);
      expect(() => liftFlowFile(text)).toThrow(message);
    });
  });

  it('ignores a stray "export const FLOW" outside the markers and lifts the real one', () => {
    const spec = HAND_BUILT_FLOWS[0];
    const text = buildFlowFileText(spec);
    const withStray = `export const FLOW = "not the real one, someone pasted this by hand";\n${text}\n// another stray:\nexport const FLOW = { version: 999 };\n`;
    const { spec: lifted } = liftFlowFile(withStray);
    expect(lifted).toEqual(spec);
  });

  it('throws LiftError naming the step index and segment id for a shape defect', () => {
    const spec = HAND_BUILT_FLOWS[1];
    const broken = JSON.parse(JSON.stringify(spec));
    broken.steps[1].segments[0].steps[0].tool = 123; // tool must be a string
    const text = buildFlowFileText(broken);
    expect(() => liftFlowFile(text)).toThrow(LiftError);
    expect(() => liftFlowFile(text)).toThrow(/step\[1\]/);
    expect(() => liftFlowFile(text)).toThrow(/02-create-seg/);
  });
});

describe('liftFlowFile: preconditions.fingerprint', () => {
  const vector = Array.from({ length: FINGERPRINT_DIMS }, (_, i) => (i % 4 ? 0 : 0.25));
  const withPreconditions = (preconditions: unknown) => {
    const spec = JSON.parse(JSON.stringify(HAND_BUILT_FLOWS[1]));
    spec.steps[1].segments[0].preconditions = preconditions;
    return buildFlowFileText(spec);
  };

  it('lifts a recorded vector verbatim, and still reads the legacy flag', () => {
    const lifted = liftFlowFile(withPreconditions({ urlPattern: 'http://localhost:5173/x', fingerprint: vector })).spec;
    expect(lifted.steps[1].segments[0].preconditions).toEqual({ urlPattern: 'http://localhost:5173/x', fingerprint: vector });
    const legacy = liftFlowFile(withPreconditions({ urlPattern: 'http://localhost:5173/x', fingerprinted: true })).spec;
    expect(legacy.steps[1].segments[0].preconditions).toEqual({ urlPattern: 'http://localhost:5173/x', fingerprinted: true });
  });

  it.each([
    ['not an array', { urlPattern: 'x', fingerprint: '0.1,0.2' }, /step\[1\] \(id "02-create"\), segment\[0\] \(id "02-create-seg"\): "preconditions\.fingerprint" must be an array of 512 numbers \(found string\)/],
    ['a truncated vector', { urlPattern: 'x', fingerprint: vector.slice(0, 100) }, /02-create-seg"\): "preconditions\.fingerprint" must have 512 entries \(found 100\)/],
    ['a non-number entry', { urlPattern: 'x', fingerprint: [...vector.slice(0, 7), '0.5', ...vector.slice(8)] }, /"preconditions\.fingerprint"\[7\] must be a finite number \(found "0\.5"\)/],
    ['a null entry', { urlPattern: 'x', fingerprint: [null, ...vector.slice(1)] }, /"preconditions\.fingerprint"\[0\] must be a finite number \(found null\)/],
    ['a legacy flag that is not true', { urlPattern: 'x', fingerprinted: 'yes' }, /"preconditions\.fingerprinted" must be true when present \(found "yes"\)/],
  ])('refuses %s with a LiftError naming the field', (_what, preconditions, message) => {
    const text = withPreconditions(preconditions);
    expect(() => liftFlowFile(text)).toThrow(LiftError);
    expect(() => liftFlowFile(text)).toThrow(message);
  });
});

describe('liftFlowFile: FLOW.recipes', () => {
  const recipes = {
    version: 1,
    recipes: [
      { id: 'r_mon', family: 'monaco', intent: 'set-value', steps: [{ action: 'click' }, { action: 'insertText', text: '{{value}}' }, { action: 'settle', ms: 400 }, { action: 'blur', target: 'textarea' }], verifyRead: '.view-lines' },
      { id: 'r_combo', family: 'aria-combobox', intent: 'select-option', steps: [{ action: 'click', target: 'page:[role="option"]', withText: '{{value}}' }] },
    ],
  };
  const withRecipes = (r: unknown) => buildFlowFileText({ ...HAND_BUILT_FLOWS[0], recipes: r } as unknown as SpecFlow);

  it('lifts a well-formed snapshot verbatim', () => {
    expect(liftFlowFile(withRecipes(recipes)).spec.recipes).toEqual(recipes);
    // absent stays absent
    expect(liftFlowFile(buildFlowFileText(HAND_BUILT_FLOWS[0])).spec.recipes).toBeUndefined();
  });

  it.each([
    ['not an object', [], /FLOW\.recipes must be an object/],
    ['a wrong version', { ...recipes, version: 2 }, /FLOW\.recipes\.version must be 1 \(found 2\)/],
    ['recipes not an array', { version: 1, recipes: {} }, /FLOW\.recipes\.recipes must be an array/],
    ['a recipe that is not an object', { version: 1, recipes: ['r_x'] }, /FLOW\.recipes\.recipes\[0\]: not an object/],
    ['a recipe with no id', { version: 1, recipes: [{ family: 'monaco', intent: 'set-value', steps: [] }] }, /FLOW\.recipes\.recipes\[0\]: missing string "id"/],
    ['a recipe with no family', { version: 1, recipes: [{ id: 'r_x', intent: 'set-value', steps: [] }] }, /recipes\[0\] \(id "r_x"\): missing string "family"/],
    ['an unknown intent', { version: 1, recipes: [{ id: 'r_x', family: 'monaco', intent: 'paste', steps: [] }] }, /recipes\[0\] \(id "r_x"\): "intent" must be one of .* \(found "paste"\)/],
    ['steps not an array', { version: 1, recipes: [{ id: 'r_x', family: 'monaco', intent: 'set-value', steps: 'click' }] }, /recipes\[0\] \(id "r_x"\): "steps" must be an array/],
    ['an unknown step action', { version: 1, recipes: [{ id: 'r_x', family: 'monaco', intent: 'set-value', steps: [{ action: 'wait' }] }] }, /recipes\[0\] \(id "r_x"\), steps\[0\]: "action" must be one of/],
    ['a non-string step text', { version: 1, recipes: [{ id: 'r_x', family: 'monaco', intent: 'set-value', steps: [{ action: 'insertText', text: 7 }] }] }, /steps\[0\]: "text" must be a string when present/],
    ['a non-string verifyRead', { version: 1, recipes: [{ id: 'r_x', family: 'monaco', intent: 'set-value', steps: [], verifyRead: 1 }] }, /"verifyRead" must be a string when present/],
  ])('refuses %s with a LiftError naming the field', (_what, bad, message) => {
    const text = withRecipes(bad);
    expect(() => liftFlowFile(text)).toThrow(LiftError);
    expect(() => liftFlowFile(text)).toThrow(message);
  });
});
