import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import ts from 'typescript';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { Flow } from '../src/skills/flow.js';
import { SkillStore, type Skill, type SkillStep } from '../src/skills/store.js';
import { VOLATILE_TOKEN_SHAPE } from '../src/shared/text.js';
import { emitFlowFile, emitSpecFile } from '../src/spec/emit.js';
import { flowToSpec, type SpecFlow, type SpecSegment, type SpecStep } from '../src/spec/ir.js';
import { compileFlow } from '../src/spec/index.js';

const FWAT2 = path.resolve('bench/results-published/fwat2-skills');
const RDFLOW = path.resolve('bench/results-published/flows/rdflow.json');

/**
 * The emitted file must be real TypeScript, not text that looks like it: a
 * generated spec that does not parse is the one failure mode a reviewer
 * cannot work around. transpileModule reports syntax diagnostics only, which
 * is exactly the question here — the file is compiled by the user's own
 * project, with their own @playwright/test types.
 */
function syntaxErrors(source: string, fileName = 'flow.ts'): string[] {
  const out = ts.transpileModule(source, {
    fileName,
    reportDiagnostics: true,
    compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext },
  });
  return (out.diagnostics ?? []).map((d) => ts.flattenDiagnosticMessageText(d.messageText, ' '));
}

type Stub = { count: () => Promise<number> };

/** A Locator stub whose count() answers from `next`, one call at a time. */
function locatorStub(next: () => number): Stub {
  return { count: async () => next() };
}

/** A Page stub for the inlined `pick`: it only ever waits. */
function pageStub(): { waitForTimeout: (ms: number) => Promise<void> } {
  return { waitForTimeout: async () => {} };
}

/**
 * The `pick` helper cut out of an emitted file and made callable, so its
 * BEHAVIOUR can be tested rather than its text. Only the final brace of the
 * function sits at column 0, which is what bounds the cut.
 */
function runnablePick(source: string): {
  pick: (page: unknown, candidates: Stub[], where: string, opts?: { any?: boolean }) => Promise<Stub>;
  drift: string[];
} {
  const consts = /const PICK_WAIT_MS = \d+;\nconst PICK_POLL_MS = \d+;/.exec(source);
  const fn = /\nasync function pick\(page: Page[\s\S]*?\n\}\n/.exec(source);
  if (!consts || !fn) throw new Error('pick helper not found in the emitted source');
  const js = ts.transpileModule(`${consts[0]}\n${fn[0]}`, {
    compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext },
  }).outputText;
  const drift: string[] = [];
  const build = new Function('DRIFT', 'console', `${js}\nreturn pick;`) as (
    d: string[],
    c: unknown,
  ) => (page: unknown, candidates: Stub[], where: string, opts?: { any?: boolean }) => Promise<Stub>;
  return { pick: build(drift, { warn: () => {} }), drift };
}

/** The FLOW constant as LIFT will read it back. */
function flowConstant(source: string): unknown {
  const body = /\/\/ @sitelooper-flow-begin\n([\s\S]*?)\n\/\/ @sitelooper-flow-end/.exec(source);
  if (!body) throw new Error('markers missing');
  return JSON.parse(body[1].replace(/^export const FLOW = /, '').replace(/;$/, ''));
}

function segment(steps: SkillStep[], over: Partial<SpecSegment> = {}): SpecSegment {
  return {
    id: 's_test1',
    template: 'do the thing with {{v1}}',
    params: { v1: { example: 'Widget A', usedIn: [1], known: true } },
    preconditions: { urlPattern: 'http://app.test/items' },
    steps,
    ...over,
  };
}

function specOf(steps: SkillStep[], over: Partial<SpecStep> = {}, flowOver: Partial<SpecFlow> = {}): SpecFlow {
  const step: SpecStep = {
    id: '01-do',
    instruction: 'do the thing',
    params: { v1: '{{name}}' },
    outputs: [],
    segments: [segment(steps)],
    ...over,
  };
  return { version: 1, name: 'demo', origin: 'http://app.test', startUrl: 'http://app.test/', vars: ['name'], steps: [step], ...flowOver };
}

const emit = (spec: SpecFlow) => emitFlowFile(spec, { tier: 'plain' }).source;

describe('emitFlowFile layout', () => {
  const source = emit(specOf([{ tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'role', role: 'button', name: 'Save' }] } }]));

  it('opens with the version marker and the do-not-edit header', () => {
    const head = source.split('\n');
    expect(head[0]).toBe('// @sitelooper-flow v1');
    expect(head[1]).toContain('Generated by sitelooper from flow "demo"');
    // the click helper takes a Locator, so a flow whose only step is a click imports the type
    expect(head[3]).toBe("import { expect, type Locator, type Page } from '@playwright/test';");
  });

  it('carries the spec verbatim between the lift markers', () => {
    const spec = specOf([{ tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'role', role: 'button', name: 'Save' }] } }]);
    expect(emit(spec)).toContain(`export const FLOW = ${JSON.stringify(spec, null, 2)};`);
    expect(flowConstant(emit(spec))).toEqual(JSON.parse(JSON.stringify(spec)));
  });

  it('declares Vars, Outputs, the steps object and runFlow', () => {
    expect(source).toContain('export type Vars = { name: string };');
    expect(source).toContain('export interface Outputs {');
    expect(source).toContain("  async '01-do'(page: Page, p: { v1: string }, outputs: Outputs): Promise<void> {");
    expect(source).toContain('export async function runFlow(page: Page, vars: Vars): Promise<Outputs> {');
    expect(source).toContain("  await page.goto('http://app.test/');");
    expect(source).toContain("  await steps['01-do'](page, { v1: vars.name }, outputs);");
    expect(syntaxErrors(source)).toEqual([]);
  });

  // DRIFT is exported unconditionally, not only when `pick` is emitted: a
  // caller's `.spec.ts` imports it once, statically, and a flow that has no
  // multi-candidate step TODAY may gain one the moment `repair` widens a
  // chain — the import in the user's own, never-rewritten file must not have
  // to change to keep compiling. The array is simply empty until a `pick`
  // call actually falls through.
  it('exports DRIFT even when the flow has no step that needs pick', () => {
    expect(source).not.toContain('async function pick');
    expect(source).toContain('export const DRIFT: string[] = [];');
  });

  it('types p as an open record when the step has no slots', () => {
    const spec = specOf([{ tool: 'back', args: {}, locators: {} }], { params: {}, segments: [segment([{ tool: 'back', args: {}, locators: {} }], { params: {} })] });
    expect(emit(spec)).toContain("async '01-do'(page: Page, p: Record<string, string>, outputs: Outputs)");
  });
});

describe('step bodies', () => {
  const one = (step: SkillStep, over?: Partial<SpecSegment>) =>
    emit(specOf([step], over ? { segments: [segment([step], over)] } : {}));

  it('renders each tool with its Playwright statement', () => {
    const loc = { target: [{ kind: 'testid' as const, attr: 'data-testid', value: 'save' }] };
    expect(one({ tool: 'click', args: { target: '@e1' }, locators: loc })).toContain("await click(page.getByTestId('save'));");
    expect(one({ tool: 'dblclick', args: { target: '@e1' }, locators: loc })).toContain(", { dbl: true });");
    expect(one({ tool: 'right_click', args: { target: '@e1' }, locators: loc })).toContain(".click({ button: 'right' });");
    // through the inlined helper, never Playwright's own fill (which fires no `change`)
    expect(one({ tool: 'fill', args: { target: '@e1', value: '{{v1}}' }, locators: loc })).toContain(
      "await fill(page.getByTestId('save'), `${p.v1}`);",
    );
    expect(one({ tool: 'type', args: { target: '@e1', text: 'abc', delay_ms: 50 }, locators: loc })).toContain(".pressSequentially('abc', { delay: 50 });");
    expect(one({ tool: 'press', args: { target: '@e1', key: 'Enter' }, locators: loc })).toContain(".press('Enter');");
    expect(one({ tool: 'select', args: { target: '@e1', option: 'Client One' }, locators: loc })).toContain(
      "await select(page.getByTestId('save'), 'Client One');",
    );
    expect(one({ tool: 'check', args: { target: '@e1', checked: true }, locators: loc })).toContain('.check();');
    expect(one({ tool: 'check', args: { target: '@e1', checked: false }, locators: loc })).toContain('.uncheck();');
    expect(one({ tool: 'goto', args: { url: 'http://app.test/x' }, locators: {} })).toContain("await page.goto('http://app.test/x');");
  });

  it('presses a key on the page when the recording had no target', () => {
    expect(one({ tool: 'press', args: { key: 'Escape' }, locators: {} })).toContain("await page.keyboard.press('Escape');");
  });

  it('arms a dialog handler before the click that raises it', () => {
    expect(one({ tool: 'dialog_expect', args: { action: 'accept' }, locators: {} })).toContain("page.once('dialog', (dialog) => dialog.accept());");
    expect(one({ tool: 'dialog_expect', args: { action: 'dismiss', count: 2 }, locators: {} })).toContain("page.on('dialog', (dialog) => dialog.dismiss());");
  });

  it('writes a labelled read into outputs, by kind', () => {
    const loc = { target: [{ kind: 'id' as const, selector: '#total' }] };
    // A read goes through readOptional even with ONE candidate: an observation
    // that cannot be re-captured must not fail the flow (see readLines).
    expect(one({ tool: 'read', args: { target: '@e1', what: 'text' }, locators: loc, label: 'total' })).toContain(
      "outputs['01-do.total'] = await readOptional(page, [\n      page.locator('#total'),\n    ], '01-do s_test1/1 target', async (loc: Locator) => (await loc.textContent()) ?? '');",
    );
    expect(one({ tool: 'read', args: { target: '@e1', what: 'value' }, locators: loc, label: 'name' })).toContain(
      "'01-do s_test1/1 target', async (loc: Locator) => await loc.inputValue());",
    );
    expect(one({ tool: 'read', args: { what: 'url' }, locators: {}, label: 'here' })).toContain("outputs['01-do.here'] = page.url();");
    expect(one({ tool: 'read_all', args: { target: '@e1', what: 'text' }, locators: loc, label: 'rows' })).toContain('.allTextContents()).join(');
  });

  it('leaves an unlabelled read as an observation', () => {
    const out = one({ tool: 'read', args: { target: '@e1', what: 'text' }, locators: { target: [{ kind: 'id', selector: '#t' }] } });
    expect(out).toContain('// observed: read text (unlabelled');
    expect(out).not.toContain('outputs[');
  });

  it('resolves a multi-candidate action through pick, never through a .or() union', () => {
    const out = one({
      tool: 'fill',
      args: { target: '@e1', value: 'x' },
      locators: {
        target: [
          { kind: 'id', selector: '#login-email' },
          { kind: 'css', selector: '[data-testid="form-dialog"] input' },
        ],
      },
    });
    expect(out).toContain('const el1 = await pick(page, [');
    expect(out).toContain("  page.locator('#login-email'),");
    expect(out).toContain('await fill(el1, ');
    // a union would be a strict-mode violation the moment a fallback matched two inputs
    expect(out).not.toContain('.or(page');
    expect(out).toContain('async function pick(page: Page, candidates: Locator[]');
    expect(out).toContain("import { expect, type Locator, type Page } from '@playwright/test';");
  });

  it('reports a fallthrough as one stable, grep-able drift line and pushes it into DRIFT', () => {
    const out = one({
      tool: 'fill',
      args: { target: '@e1', value: 'x' },
      locators: {
        target: [
          { kind: 'id', selector: '#login-email' },
          { kind: 'css', selector: '[data-testid="form-dialog"] input' },
        ],
      },
    });
    expect(out).toContain("const el1 = await pick(page, [");
    expect(out).toContain("  page.locator('#login-email'),");
    expect(out).toContain("  page.locator('[data-testid=\"form-dialog\"] input'),");
    expect(out).toContain("], '01-do s_test1/1 target');");
    expect(out).toContain('if (won > 0) {');
    expect(out).toContain(
      "const line = `[sitelooper drift] ${where}: primary ${String(candidates[0])} missed; used #${won + 1} ${String(candidates[won])}`;",
    );
    expect(out).toContain('console.warn(line);');
    expect(out).toContain('DRIFT.push(line);');
    expect(syntaxErrors(out)).toEqual([]);
  });

  /**
   * fwrd42, `sitelooper repair` had promoted
   * `page.locator('tr', { hasText: '{{v5}}' }).locator('td:nth-of-type(1)')` to
   * primary off live replay evidence, yet the compiled spec logged it as missed
   * on ~40% of runs and took `getByText` (twice a purely structural fallback)
   * instead. Not ambiguity and not hasText semantics: the repair-desk bench
   * defers its parts refetch ~500ms BY DESIGN, landing on a poll boundary, and
   * a pass of `pick` is not one instant — every count() is its own round trip.
   * Measured, the scoped primary counted 0 at t, getByText counted 1 at t+3ms,
   * and the primary counted 1 again 3ms after that.
   */
  describe('pick re-checks the candidates ahead before demoting the primary', () => {
    const scopedChain: SkillStep = {
      tool: 'wait_for',
      args: { target: '@e1', state: 'visible' },
      locators: {
        target: [
          { kind: 'scoped', container: 'tr', hasText: '{{v1}}', selector: 'td:nth-of-type(1)' },
          { kind: 'text', text: '{{v1}}' },
        ],
      },
    };

    it('emits the scoped primary ahead of the text fallback', () => {
      const out = one(scopedChain);
      expect(out).toContain("  page.locator('tr', { hasText: `${p.v1}` }).locator('td:nth-of-type(1)'),");
      expect(out).toContain('  page.getByText(`${p.v1}`, { exact: true }),');
      expect(syntaxErrors(out)).toEqual([]);
    });

    it('keeps the primary when it only missed because the row painted mid-pass', async () => {
      const { pick, drift } = runnablePick(one(scopedChain));
      // The primary is sampled first in every pass, so it is the candidate a
      // paint at the poll boundary makes look absent. It is there 3ms later.
      let samples = 0;
      const primary = locatorStub(() => (++samples === 1 ? 0 : 1));
      const fallback = locatorStub(() => 1);
      expect(await pick(pageStub(), [primary, fallback], 'w')).toBe(primary);
      expect(drift).toEqual([]);
    });

    it('still falls through, and still reports drift, when the primary is really gone', async () => {
      const { pick, drift } = runnablePick(one(scopedChain));
      const primary = locatorStub(() => 0);
      const fallback = locatorStub(() => 1);
      expect(await pick(pageStub(), [primary, fallback], '01-do s_test1/1 target')).toBe(fallback);
      expect(drift).toHaveLength(1);
      expect(drift[0]).toContain('[sitelooper drift] 01-do s_test1/1 target: primary');
      expect(drift[0]).toContain('used #2');
    });

    it('does not let the re-check hand back a candidate that is ambiguous', async () => {
      const { pick, drift } = runnablePick(one(scopedChain));
      // Two rows carry the text: replay skips a candidate that is not unique
      // and so must the spec — the re-check is about WHEN a candidate is
      // sampled, never about relaxing what counts as resolved.
      const primary = locatorStub(() => 2);
      const fallback = locatorStub(() => 1);
      expect(await pick(pageStub(), [primary, fallback], 'w')).toBe(fallback);
      expect(drift).toHaveLength(1);
    });
  });

  it('places a @step location comment before each step\'s first statement, in order', () => {
    const stepA: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#a' }] } };
    const stepB: SkillStep = { tool: 'click', args: { target: '@e2' }, locators: { target: [{ kind: 'id', selector: '#b' }] } };
    const out = emit(specOf([stepA, stepB]));
    const lines = out.split('\n');
    const stepLines = lines.map((l) => l.trim()).filter((l) => l.startsWith('// @step '));
    expect(stepLines).toEqual(['// @step 01-do s_test1/1', '// @step 01-do s_test1/2']);
    // each @step comment is the line immediately above its own statement
    const i1 = lines.findIndex((l) => l.trim() === '// @step 01-do s_test1/1');
    // the settle replay does at the top of runOneStep, then the step itself
    expect(lines[i1 + 1].trim()).toBe('await settle(page);');
    expect(lines[i1 + 2]).toContain("await click(page.locator('#a'));");
    const i2 = lines.findIndex((l) => l.trim() === '// @step 01-do s_test1/2');
    expect(lines[i2 + 1].trim()).toBe('await settle(page);');
    expect(lines[i2 + 2]).toContain("await click(page.locator('#b'));");
  });

  it('drops a duplicate candidate expression rather than resolving it twice', () => {
    const out = one({
      tool: 'click',
      args: { target: '@e1' },
      locators: { target: [{ kind: 'id', selector: '#go' }, { kind: 'css', selector: '#go' }] },
    });
    expect(out).toContain("await click(page.locator('#go'));");
    expect(out).not.toContain('pick(page');
  });

  it('inlines the pick helper only when a step needs it', () => {
    const out = one({ tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#b' }] } });
    expect(out).not.toContain('async function pick');
    // and nothing pick alone pulls in: no poll constants, no drift bookkeeping in the body
    expect(out).not.toContain('const PICK_WAIT_MS');
  });

  it('imports Locator only when a helper takes one', () => {
    const noHelper = one({ tool: 'read', args: { what: 'url' }, locators: {}, label: 'here' });
    expect(noHelper).toContain("import { expect, type Page } from '@playwright/test';");
    expect(noHelper).not.toContain('async function click');
    const clicked = one({ tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#b' }] } });
    expect(clicked).toContain("import { expect, type Locator, type Page } from '@playwright/test';");
  });

  it('lets a read_all match many, which is what it is for', () => {
    const out = one({
      tool: 'read_all',
      args: { target: '@e1', what: 'text' },
      locators: { target: [{ kind: 'id', selector: '#rows' }, { kind: 'css', selector: '.row' }] },
      label: 'rows',
    });
    expect(out).toMatch(/], '[^']+', async \(loc: Locator\) => \(await loc\.allTextContents\(\)\)[^\n]*, \{ any: true \}\);/);
  });

  it('names what Tier 2 loses when a point candidate is dropped', () => {
    const out = one({
      tool: 'click',
      args: { target: '@e1' },
      locators: { target: [{ kind: 'role', role: 'button', name: 'Save' }, { kind: 'point', x: 10, y: 20, w: 5, h: 5, role: 'button', tag: 'button', vw: 800, vh: 600 }] },
    });
    expect(out).toContain('// TODO: dropped the recorded position fallback (button at 10,20)');
  });

  it('falls back to a TODO when no candidate can be expressed', () => {
    const spec = specOf([{ tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'point', x: 1, y: 2, w: 3, h: 4, role: null, tag: 'div', vw: 800, vh: 600 }] } }]);
    const { source, warnings } = emitFlowFile(spec, { tier: 'plain' });
    expect(source).toContain('// TODO: no locator this compiler can express for click');
    expect(warnings.some((w) => w.includes('no locator a spec can express'))).toBe(true);
  });
});

describe('expectations', () => {
  const withExpect = (expectation: SkillStep['expect'], tool = 'click', args: Record<string, unknown> = { target: '@e1' }) =>
    emit(specOf([{ tool, args, locators: { target: [{ kind: 'id', selector: '#b' }] }, expect: expectation }]));

  it('turns a url pattern into an anchored regex, ids wildcarded and slots escaped', () => {
    expect(withExpect({ urlPattern: 'http://app.test/items/:id' })).toContain(
      'await expect(page).toHaveURL(new RegExp(`^http://app\\\\.test/items/[^/]+(?:[?#].*)?$`));',
    );
    expect(withExpect({ urlPattern: 'http://app.test/items/{{v1}}' })).toContain('${escapeRe(p.v1)}');
    // the query is not part of a page's identity; the hash route is
    expect(withExpect({ urlPattern: 'http://app.test/a?q=1#/detail' })).toContain('(?:\\\\?[^#]*)?#/detail$');
  });

  it('matches a query-shaped hash as unordered STATE, the way urlMatches does (the odoo failure)', () => {
    const out = withExpect({ urlPattern: 'http://app.test/web#action=:id&cids=1&menu_id={{v1}}' });
    expect(out).toContain('await expect(page).toHaveURL((url: URL) => hashMatch(url, new RegExp(');
    expect(out).toContain("[['action', null], ['cids', '1'], ['menu_id', `${p.v1}`]]));");
    expect(out).toContain('function hashState(href: string): Map<string, string> | null {');
    // a hash ROUTE is ordered, and keeps the regex form
    const route = withExpect({ urlPattern: 'http://app.test/a#/detail/:id' });
    expect(route).toContain('toHaveURL(new RegExp(');
    expect(route).not.toContain('hashMatch');
    // and so does a url with no fragment at all
    expect(withExpect({ urlPattern: 'http://app.test/items/:id' })).not.toContain('hashMatch');
  });

  it('accepts the recorded state in any order, with extra pairs, and refuses a wrong value', () => {
    const { hashMatch } = runnableHelpers(withExpect({ urlPattern: 'http://app.test/web#action=316&cids=1' }));
    const head = /^http:\/\/app\.test\/web$/;
    const want: [string, string | null][] = [
      ['action', '316'],
      ['cids', '1'],
    ];
    // the SECOND cloud run's url, pair for pair, in another order
    expect(hashMatch(new URL('http://app.test/web#cids=1&model=sale.order&action=316'), head, want)).toBe(true);
    expect(hashMatch(new URL('http://app.test/web#action=317&cids=1'), head, want)).toBe(false);
    // a pair the pattern names with a LITERAL must be there
    expect(hashMatch(new URL('http://app.test/web#action=316'), head, want)).toBe(false);
    // a :id/:var one is app-minted state: anything, or absent
    expect(
      hashMatch(new URL('http://app.test/web#action=316'), head, [
        ['action', '316'],
        ['cids', null],
      ]),
    ).toBe(true);
    // another page, or a route where state was recorded, is not this page
    expect(hashMatch(new URL('http://app.test/other#action=316&cids=1'), head, want)).toBe(false);
    expect(hashMatch(new URL('http://app.test/web#/action/316'), head, want)).toBe(false);
  });

  it('rebuilds a masked line name as the token shape it stood for, not as a literal (the kanboard failure)', () => {
    const out = withExpect({ addedContains: ['- heading "Due {{*}}"'] });
    // the literal '{{*}}' matched nothing on any page, which is what failed
    expect(out).not.toContain("name: 'Due {{*}}'");
    expect(out).toContain("page.getByRole('heading', { name: new RegExp(`Due ");
    // the token shape, because the mask only ever covered a clock or a date:
    // '.*' would let a heading called "Due date" satisfy it
    // (doubled: the shape is regex source living inside a template literal)
    expect(out).toContain(VOLATILE_TOKEN_SHAPE.replace(/\\/g, '\\\\'));
    // a presence check stays a substring match (Playwright ignores `exact` for
    // a RegExp, so the anchoring has to carry that decision)
    expect(out).not.toContain('new RegExp(`^Due ');
    expect(syntaxErrors(out)).toEqual([]);
  });

  it('leaves a line that is nothing BUT wildcards as an observation: it names no element', () => {
    const out = withExpect({ addedContains: ['- textbox "{{*}} {{*}}": {{*}}'] });
    expect(out).toContain('// observed (nothing nameable in it): - textbox "{{*}} {{*}}": {{*}}');
    expect(out).not.toContain('toBeVisible');
    expect(out).not.toContain('getByRole');
  });

  it('inlines escapeRe only when a body uses it', () => {
    expect(withExpect({ urlPattern: 'http://app.test/items/{{v1}}' })).toContain('function escapeRe(s: string): string {');
    expect(withExpect({ urlPattern: 'http://app.test/items/:id' })).not.toContain('function escapeRe');
  });

  it('groups the recorded lines into one any-of assertion per group, as the effect gate has them', () => {
    const out = withExpect({
      addedContains: ['- heading "{{v1}} Widget"', '- status "Loading…"', '- generic "sidebar"', '- tab "New Project"'],
    });
    // the parameterised group is its own assertion: those lines are the hard gate
    expect(out).toContain("await expect(page.getByRole('heading', { name: `${p.v1} Widget`, exact: false }).first()).toBeVisible();");
    // the plain lines are ONE union, not one assertion each — replay stops only when none of them shows
    expect(out).toContain("await expect(page.getByRole('generic', { name: 'sidebar', exact: false })");
    expect(out).toContain(".or(page.getByRole('tab', { name: 'New Project', exact: false }))");
    expect(out.split('\n').filter((l) => l.includes('toBeVisible')).length).toBe(2);
    // a transient line never becomes an assertion (the FLOW constant still records it)
    expect(out).not.toContain("getByRole('status'");
  });

  it('names the presence check loosely, because a recorded line is not a Playwright name', () => {
    expect(withExpect({ addedContains: ['- menu "View Details Remove"'] })).toContain(
      "await expect(page.getByRole('menu', { name: 'View Details Remove', exact: false }).first()).toBeVisible();",
    );
  });

  it('drops a fill echo in favour of the consequential change', () => {
    const out = withExpect({ addedContains: ['- textbox "": {{v1}}', '- heading "{{v1}}"'] }, 'fill', { target: '@e1', value: '{{v1}}' });
    expect(out).toContain("page.getByRole('heading'");
    expect(out).not.toContain('- textbox ""');
  });

  it('keeps a lone echo as an observation rather than inventing a locator', () => {
    const out = withExpect({ addedContains: ['- textbox "": {{v1}}'] }, 'fill', { target: '@e1', value: '{{v1}}' });
    expect(out).toContain('// observed (nothing nameable in it): - textbox "": {{v1}}');
    expect(out).not.toContain('toBeVisible');
  });

  it('asserts a url only where the pattern changes', () => {
    const at = (pattern: string): SkillStep => ({
      tool: 'click',
      args: { target: '@e1' },
      locators: { target: [{ kind: 'id', selector: '#b' }] },
      expect: { urlPattern: pattern },
    });
    const source = emit(specOf([at('http://app.test/a'), at('http://app.test/a'), at('http://app.test/b')]));
    const asserted = source.split('\n').filter((l) => l.includes('toHaveURL'));
    expect(asserted.length).toBe(2);
    expect(asserted[1]).toContain('/b');
  });

  it('leaves an alert as a comment — a toast is volatile', () => {
    expect(withExpect({ alertContains: 'Saved 3 items' })).toContain('// expected alert containing "Saved 3 items"');
  });
});

describe('preconditions, minting and loops', () => {
  it('checks a bound identity marker at segment entry and skips an unbound one', () => {
    const step: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#b' }] } };
    const bound = emit(specOf([step], { segments: [segment([step], { preconditions: { urlPattern: 'http://app.test/x', requireText: ['{{v1}}'] } })] }));
    expect(bound).toContain('await expect(page.getByText(`${p.v1}`).first()).toBeVisible();');
    const unbound = emit(
      specOf([step], { segments: [segment([step], { params: {}, preconditions: { urlPattern: 'http://app.test/x', requireText: ['{{v9}}'] } })] }),
    );
    expect(unbound).toContain('is unbound here — nothing to check.');
  });

  it('comments the precondition url rather than asserting it', () => {
    const step: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#b' }] } };
    expect(emit(specOf([step]))).toContain('// recorded on a page matching http://app.test/items');
  });

  it('binds a derived value off the live url after the step that mints it', () => {
    const step: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#save' }] }, mints: { at: 'p1' } };
    const source = emit(specOf([step], { segments: [segment([step], { derived: { d1: { step: 1, at: 'p1', example: '42' } } })] }));
    expect(source).toContain('const urlBefore1 = page.url();');
    expect(source).toContain("p.d1 = await urlPartWhen(page, 'p1', urlBefore1);");
    expect(source).toContain('function urlPart(url: string, label: string): string {');
    expect(source).toContain("// This step CREATES a record (its id is url part 'p1')");
    // a minted slot is declared on p and starts empty: only the live run can fill it
    expect(source).toContain("await steps['01-do'](page, { d1: '', v1: vars.name }, outputs);");
  });

  it('unrolls a folded loop as a capped for-loop on the first match', () => {
    const body: SkillStep[] = [{ tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'role', role: 'button', name: 'Remove' }] } }];
    const loop: SkillStep = { tool: 'loop', args: {}, locators: {}, body, while: [{ kind: 'role', role: 'button', name: 'Remove' }], max: 7 };
    const source = emit(specOf([loop]));
    expect(source).toContain("const guard1 = page.getByRole('button', { name: 'Remove', exact: true });");
    expect(source).toContain('for (let i = 0; i < 7 && (await guard1.count()) > 0; i++) {');
    expect(source).toContain("await click((page.getByRole('button', { name: 'Remove', exact: true })).first());");
    expect(source).not.toContain('.or(page');
    expect(source).toContain('// FIRST match');
    expect(syntaxErrors(source)).toEqual([]);
  });
});

describe('flow-level wiring', () => {
  it('threads vars, step outputs and env secrets into the call site', () => {
    const step: SkillStep = { tool: 'fill', args: { target: '@e1', value: '{{v1}}' }, locators: { target: [{ kind: 'id', selector: '#i' }] } };
    const spec = specOf([step], {
      params: { v1: '{{name}}', v2: '{{02-b.title}}', v3: 'literal-{{name}}', v4: '{{env:BENCH_PASSWORD}}' },
      segments: [
        segment([step], {
          params: {
            v1: { example: 'a', usedIn: [1] },
            v2: { example: 'b', usedIn: [1] },
            v3: { example: 'c', usedIn: [1] },
            v4: { example: 'd', usedIn: [1] },
          },
        }),
      ],
    });
    const source = emit(spec);
    expect(source).toContain("v1: vars.name");
    expect(source).toContain("v2: outputs['02-b.title'] ?? ''");
    expect(source).toContain('v3: `literal-${vars.name}`');
    expect(source).toContain("v4: process.env.BENCH_PASSWORD ?? ''");
    expect(syntaxErrors(source)).toEqual([]);
  });

  it('publishes the end-url outputs a later step refers to (the grafana failure)', () => {
    const step: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#save' }] } };
    const producer: SpecStep = { id: '02-create', instruction: 'create it', params: { v1: 'x' }, outputs: [], segments: [segment([step])] };
    const consumer: SpecStep = {
      id: '03-add',
      instruction: 'add to it',
      params: { v1: 'http://app.test/d/{{02-create.url.p1}}/notes' },
      outputs: [],
      segments: [segment([step])],
    };
    const out = emit({ version: 1, name: 'demo', origin: 'http://app.test', startUrl: 'http://app.test/', vars: [], steps: [producer, consumer] });
    // the producing step's body publishes it; the consuming call site reads it
    expect(out).toContain("outputs['02-create.url.p1'] = await urlPartWhen(page, 'p1');");
    expect(out).toContain("v1: `http://app.test/d/${outputs['02-create.url.p1'] ?? ''}/notes`");
    // and only what something reads: an output nobody consumes is noise
    expect(out).not.toContain("outputs['03-add.url");
    expect(out).not.toContain("outputs['02-create.url']");
    expect(syntaxErrors(out)).toEqual([]);
  });

  it('publishes the whole end url too when that is what a later step names', () => {
    const step: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#save' }] } };
    const producer: SpecStep = { id: '02-create', instruction: 'create it', params: {}, outputs: [], segments: [segment([step])] };
    const consumer: SpecStep = { id: '03-add', instruction: 'add', params: { v1: '{{02-create.url}}' }, outputs: [], segments: [segment([step])] };
    const out = emit({ version: 1, name: 'demo', origin: 'http://app.test', startUrl: 'http://app.test/', vars: [], steps: [producer, consumer] });
    expect(out).toContain("outputs['02-create.url'] = page.url();");
    expect(out).toContain("v1: outputs['02-create.url'] ?? ''");
  });

  it('inlines a recorded value with a warning when the flow binds no slot', () => {
    const step: SkillStep = { tool: 'fill', args: { target: '@e1', value: '{{v1}}' }, locators: { target: [{ kind: 'id', selector: '#i' }] } };
    const { source, warnings } = emitFlowFile(specOf([step], { params: {} }), { tier: 'plain' });
    expect(source).toContain("v1: 'Widget A' /* recorded value; no flow binding */");
    expect(warnings).toContain('01-do: slot v1 has no flow binding — the recorded value is inlined');
  });

  it('throws in the body of a step with no converged procedure', () => {
    const spec = specOf([], { segments: [], instruction: 'archive the ticket' });
    const source = emit(spec);
    expect(source).toContain('// TODO: no converged procedure for "archive the ticket"');
    expect(source).toContain("throw new Error('step 01-do has no converged procedure");
    expect(syntaxErrors(source)).toEqual([]);
  });
});

describe('emitSpecFile', () => {
  it('is a thin user-owned scaffold that imports the generated half', () => {
    const source = emitSpecFile(specOf([{ tool: 'back', args: {}, locators: {} }]));
    expect(source).toContain("import { runFlow, steps, DRIFT } from './demo.flow';");
    expect(source).toContain("const outputs = await runFlow(page, { name: process.env.NAME ?? '' });");
    expect(source).toContain('sitelooper never rewrites it');
    expect(source).toContain("DRIFT.length");
    expect(syntaxErrors(source, 'demo.spec.ts')).toEqual([]);
  });
});

describe('the fwat2 store, every skill as a one-step flow', () => {
  const store = new SkillStore(FWAT2);
  const skills = store.all();

  it('has the store the rest of this suite compiles', () => {
    expect(skills.length).toBe(18);
  });

  for (const skill of skills) {
    it(`compiles ${skill.id} to a parsable spec`, () => {
      const flow: Flow = {
        name: `one-${skill.id}`,
        origin: skill.origin,
        startUrl: skill.origin + '/',
        vars: [],
        steps: [{ id: '01-do', instruction: skill.template, skill: skill.id, outputs: [], recorded: {} }],
        provenance: { session: 'test', created: new Date(0).toISOString() },
      };
      const { spec, warnings } = flowToSpec(flow, store);
      expect(spec.steps[0].segments.length).toBeGreaterThan(0);
      if (skill.status === 'demoted') expect(warnings.join(' ')).toContain('demoted');
      const { source } = emitFlowFile(spec, { tier: 'plain' });
      expect(syntaxErrors(source, `${skill.id}.flow.ts`)).toEqual([]);
      expect(flowConstant(source)).toEqual(JSON.parse(JSON.stringify(spec)));
      expect(syntaxErrors(emitSpecFile(spec), `${skill.id}.spec.ts`)).toEqual([]);
    });
  }

  it('follows a seq chain into every segment of the procedure', () => {
    const chained = skills.find((s: Skill) => s.seq)!;
    const flow: Flow = {
      name: 'chained',
      origin: chained.origin,
      startUrl: chained.origin + '/',
      vars: [],
      steps: [{ id: '01-open', instruction: chained.template, skill: chained.id, outputs: [], recorded: {} }],
      provenance: { session: 'test', created: new Date(0).toISOString() },
    };
    const { spec } = flowToSpec(flow, store);
    expect(spec.steps[0].segments.map((s) => s.id)).toEqual(
      skills.filter((s: Skill) => s.seq?.chain === chained.seq!.chain).sort((a, b) => a.seq!.index - b.seq!.index).map((s) => s.id),
    );
  });

  it('emits the real statements for the delete-and-archive skill', () => {
    const skill = store.get('s_f2ee63')!;
    const flow: Flow = {
      name: 'delete-both',
      origin: skill.origin,
      startUrl: skill.origin + '/project-manager',
      vars: ['runid'],
      steps: [{ id: '01-do', instruction: skill.template, skill: skill.id, params: { v1: '{{runid}}' }, outputs: [], recorded: {} }],
      provenance: { session: 'test', created: new Date(0).toISOString() },
    };
    const { source } = emitFlowFile(flowToSpec(flow, store).spec, { tier: 'plain' });
    // the identity-scoped primary, its hasText guard on the fallbacks, and the dialog arming
    expect(source).toContain("page.locator('div.data-list-row', { hasText: `${p.v2}` })");
    expect(source).toContain('.filter({ hasText: `${p.v2}` })');
    expect(source).toContain("page.once('dialog', (dialog) => dialog.accept());");
    expect(source).toContain('await expect(page).toHaveURL(new RegExp(`^http://localhost:5173/project-manager');
    expect(source).toContain("v1: vars.runid");
  });
});

describe('flowToSpec over a published flow', () => {
  it('reports every step of a flow whose skills are not in the store', () => {
    const flow = JSON.parse(fs.readFileSync(RDFLOW, 'utf8')) as Flow;
    const { spec, warnings } = flowToSpec(flow, new SkillStore(FWAT2));
    expect(spec.steps.map((s) => s.id)).toEqual(flow.steps.map((s) => s.id));
    expect(warnings.filter((w) => w.includes('no converged procedure')).length).toBe(flow.steps.length);
    const { source } = emitFlowFile(spec, { tier: 'plain' });
    expect(syntaxErrors(source, 'rdflow.flow.ts')).toEqual([]);
    expect((source.match(/has no converged procedure/g) ?? []).length).toBeGreaterThanOrEqual(flow.steps.length);
  });
});

describe('compileFlow', () => {
  let dir: string;
  beforeAll(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sl-spec-'));
  });
  afterAll(() => fs.rmSync(dir, { recursive: true, force: true }));

  it('writes both files, then never rewrites the user-owned one', () => {
    const out = path.join(dir, 'out');
    const first = compileFlow(RDFLOW, { store: new SkillStore(FWAT2), outDir: out });
    expect(first.flowFile).toBe(path.join(out, 'rdflow.flow.ts'));
    expect(first.specFile).toBe(path.join(out, 'rdflow.spec.ts'));
    expect(first.compilable).toBe(false);

    fs.appendFileSync(first.specFile!, '\n// mine\n');
    const again = compileFlow(RDFLOW, { store: new SkillStore(FWAT2), outDir: out });
    expect(again.specFile).toBeNull();
    expect(fs.readFileSync(path.join(out, 'rdflow.spec.ts'), 'utf8')).toContain('// mine');
    // the generated half is regenerated every time
    expect(fs.readFileSync(again.flowFile, 'utf8')).toContain('// @sitelooper-flow v1');

    const forced = compileFlow(RDFLOW, { store: new SkillStore(FWAT2), outDir: out, force: true });
    expect(forced.specFile).not.toBeNull();
    expect(fs.readFileSync(path.join(out, 'rdflow.spec.ts'), 'utf8')).not.toContain('// mine');
  });

  it('refuses a flow it cannot find', () => {
    expect(() => compileFlow('no-such-flow', { outDir: dir })).toThrow(/no flow named/);
  });
});

/**
 * A wait for the target to be GONE is satisfied by its absence. pick() would
 * throw on a chain nothing resolves, so the emitter uses the union of every
 * candidate under toBeHidden instead — fwrd42's 06-report waits for a deleted
 * part's text and used to fail the compiled spec and the replay alike.
 */
describe('wait_for on an absent target', () => {
  const one = (step: SkillStep) => emit(specOf([step]));
  const gone: SkillStep = {
    tool: 'wait_for',
    args: { target: 'text=x', state: 'hidden' },
    locators: { target: [{ kind: 'text', text: '{{v4}}' }, { kind: 'css', selector: 'td.name' }] },
  };
  it('asserts the union is hidden instead of picking a candidate', () => {
    const out = one(gone);
    expect(out).not.toContain('await pick(');
    expect(out).toContain("await expect((page.getByText(`${p.v4}`, { exact: true })");
    expect(out).toContain(".or(page.locator('td.name'))).first()).toBeHidden();");
    expect(syntaxErrors(out)).toEqual([]);
  });
  it('does the same for a count of zero', () => {
    const out = one({ ...gone, args: { target: 'text=x', state: 'count', count: 0 } });
    expect(out).not.toContain('await pick(');
    expect(out).toContain('.first()).toHaveCount(0);');
  });
});

/**
 * The inlined helpers, cut out of an emitted file whole and made callable —
 * the same trick `runnablePick` plays, generalised: everything between the
 * DRIFT export and the steps object IS the helper block, and running it is
 * the only way to test what it DOES rather than what it says.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function runnableHelpers(source: string, con: unknown = { warn: () => {} }): Record<string, any> {
  const block = /export const DRIFT: string\[\] = \[\];\n([\s\S]*?)\nexport const steps = \{/.exec(source);
  if (!block) throw new Error('helper block not found in the emitted source');
  const js = ts.transpileModule(block[1], {
    compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext },
  }).outputText;
  const names = [...block[1].matchAll(/^(?:async )?function (\w+)/gm)].map((m) => m[1]);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const build = new Function('DRIFT', 'console', `${js}\nreturn { ${names.join(', ')} };`) as (d: string[], c: unknown) => Record<string, any>;
  return build([], con);
}

/** A Page stub whose url() answers from a script, one call at a time. */
function urlPageStub(urls: string[]) {
  let i = 0;
  const waits: number[] = [];
  return {
    page: {
      url: () => urls[Math.min(i++, urls.length - 1)],
      waitForTimeout: async (ms: number) => {
        waits.push(ms);
      },
    },
    waits,
  };
}

describe('a derived value is read after the navigation lands', () => {
  const minting: SkillStep = {
    tool: 'click',
    args: { target: '@e1' },
    locators: { target: [{ kind: 'id', selector: '#login' }] },
  };
  const source = emit(
    specOf([minting], { segments: [segment([minting], { derived: { d1: { step: 1, at: 'q.action', example: '123' } } })] }),
  );

  it('captures the url before the action and binds the part afterwards', () => {
    const lines = source.split('\n').map((l) => l.trim());
    const before = lines.indexOf('const urlBefore1 = page.url();');
    const acted = lines.indexOf("await click(page.locator('#login'));");
    const bound = lines.findIndex((l) => l.startsWith("p.d1 = await urlPartWhen(page, 'q.action', urlBefore1);"));
    expect(before).toBeGreaterThan(-1);
    expect(before).toBeLessThan(acted);
    expect(acted).toBeLessThan(bound);
    // the recorded example survives as the comment it always was
    expect(lines[bound]).toContain('// recorded example: 123');
    expect(syntaxErrors(source)).toEqual([]);
  });

  it('inlines urlPartWhen and the urlPart it depends on, and only when a step mints', () => {
    expect(source).toContain("async function urlPartWhen(page: Page, label: string, urlBefore = ''): Promise<string> {");
    expect(source).toContain("async function urlPartsWhen(page: Page, labels: string[], urlBefore = ''): Promise<string[]> {");
    expect(source).toContain('function urlPart(url: string, label: string): string {');
    expect(source).toContain('const PICK_WAIT_MS = 3000;');
    const plain = emit(specOf([minting]));
    expect(plain).not.toContain('urlPartWhen');
    expect(plain).not.toContain('function urlPart(');
  });

  it('reads the part straight off the url after a goto, which awaits its own navigation', () => {
    const step: SkillStep = { tool: 'goto', args: { url: 'http://app.test/x' }, locators: {} };
    const out = emit(specOf([step], { segments: [segment([step], { derived: { d1: { step: 1, at: 'p1', example: 'x' } } })] }));
    expect(out).toContain("p.d1 = urlPart(page.url(), 'p1');");
    expect(out).not.toContain('urlBefore');
  });

  it('waits for the url to change before it believes a part (the odoo failure)', async () => {
    const { urlPartWhen } = runnableHelpers(source);
    // the click has fired but the SPA has not routed yet: two reads of the old
    // url, then the one the step navigated to
    const before = 'http://app.test/web';
    const { page, waits } = urlPageStub([before, before, 'http://app.test/web#action=123&cids=1']);
    expect(await urlPartWhen(page, 'q.action', before)).toBe('123');
    expect(waits).toEqual([100, 100]);
  });

  it('falls back to whatever is there at the deadline rather than hanging', async () => {
    const { urlPartWhen } = runnableHelpers(source);
    const before = 'http://app.test/web#action=7';
    const { page, waits } = urlPageStub([before]);
    expect(await urlPartWhen(page, 'q.action', before)).toBe('7');
    // replay's own allowance for a url: settleDom (2s) and then expectedUrl's
    // own 3s resolve window, not pick's 3s
    expect(waits.length).toBe(5000 / 100);
  });

  it('binds every part of a step in ONE wait, so none is read off a half-built url', async () => {
    const two = specOf([minting], {
      segments: [
        segment([minting], {
          derived: { d1: { step: 1, at: 'q.action', example: '123' }, d2: { step: 1, at: 'q.cids', example: '1' } },
        }),
      ],
    });
    const out = emit(two);
    expect(out).toContain("const bound1 = await urlPartsWhen(page, ['q.action', 'q.cids'], urlBefore1);");
    expect(out).toContain('p.d1 = bound1[0]; // recorded example: 123');
    expect(out).toContain('p.d2 = bound1[1]; // recorded example: 1');
    expect(syntaxErrors(out)).toEqual([]);

    const { urlPartsWhen } = runnableHelpers(out);
    // odoo's shape: cids lands first and action arrives a beat later. Bound
    // one at a time, action would have been read as '' off the middle url.
    const before = 'http://app.test/web';
    const { page, waits } = urlPageStub([before, 'http://app.test/web#cids=1', 'http://app.test/web#action=123&cids=1']);
    expect(await urlPartsWhen(page, ['q.action', 'q.cids'], before)).toEqual(['123', '1']);
    expect(waits).toEqual([100, 100]);
  });

  it('waits the window replay effectively allows a url, not the shorter one pick uses', () => {
    expect(source).toContain('const URL_WAIT_MS = 5000;');
  });

  it('publishes the minted id when nothing else reads the settled url', () => {
    const mints: SkillStep = { ...minting, mints: { at: 'p2' } };
    const out = emit(specOf([mints]));
    expect(out).toContain("outputs['01-do.minted'] = await urlPartWhen(page, 'p2', urlBefore1);");
  });
});

describe('the diagnostics a cloud run has to read the failure from', () => {
  const step: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#a' }, { kind: 'css', selector: '.b' }] } };

  it('says where the step was and where the browser was when no locator resolved', () => {
    const out = emit(specOf([step]));
    expect(out).toContain('resolved at ${where} (page is at ${page.url()}): ');
  });

  it('logs a skipped opener click, so a bench log shows the click that never happened', () => {
    const opener: SkillStep = { ...step, expect: { addedContains: ['- dialog "Save dashboard"'] } };
    expect(emit(specOf([opener]))).toContain(
      "console.log('[sitelooper skip] 01-do s_test1/1: recorded popup already showing — click skipped');",
    );
  });
});

describe('a click that opens a popup is a toggle', () => {
  const opener: SkillStep = {
    tool: 'click',
    args: { target: '@e1' },
    locators: { target: [{ kind: 'role', role: 'button', name: 'Edit the task' }] },
    expect: { addedContains: ['- dialog "Edit the task"', '- button "Save"'] },
  };
  const source = emit(specOf([opener]));

  it('guards the pick and the click with the recorded opener effect', () => {
    expect(source).toContain('// This click OPENS a popup, which makes it a toggle: replay skips it when the');
    expect(source).toContain('(already in effect)');
    // exact names, unlike the effect assertions below: a false positive HERE
    // skips the click, so the guard is as strict as replay's own line-exact
    // lineShows is.
    expect(source).toContain(
      'if (await page.getByRole(\'dialog\', { name: \'Edit the task\', exact: true })\n' +
        '      .or(page.getByRole(\'button\', { name: \'Save\', exact: true }))\n' +
        '      .first().isVisible().catch(() => false)) {',
    );
    expect(source).toContain('} else {');
    // the action itself moved inside the else branch, indented with it
    expect(source).toContain("      await click(page.getByRole('button', { name: 'Edit the task', exact: true }));");
    expect(syntaxErrors(source)).toEqual([]);
  });

  it('wraps the resolution too, not only the click', () => {
    const many: SkillStep = {
      ...opener,
      locators: {
        target: [
          { kind: 'role', role: 'button', name: 'Edit the task' },
          { kind: 'id', selector: '#edit' },
        ],
      },
    };
    const lines = emit(specOf([many])).split('\n');
    const guard = lines.findIndex((l) => l.trim().startsWith('if (await page.getByRole('));
    const picked = lines.findIndex((l) => l.includes('= await pick(page, ['));
    expect(guard).toBeGreaterThan(-1);
    expect(picked).toBeGreaterThan(guard);
  });

  it('leaves a click with no popup effect alone', () => {
    const plain: SkillStep = { ...opener, expect: { addedContains: ['- text: Saved', '- button "Save"'] } };
    const out = emit(specOf([plain]));
    expect(out).not.toContain('already in effect');
    expect(out).not.toContain('} else {');
  });

  it("ignores a popup line only this run's own value produced", () => {
    const parameterised: SkillStep = { ...opener, expect: { addedContains: ['- dialog "{{v1}}"'] } };
    expect(emit(specOf([parameterised]))).not.toContain('already in effect');
  });
});

type Attempt = { kind: 'click' | 'dblclick' | 'scroll' | 'evaluate'; force?: boolean };

/** A Locator stub for the inlined `click`, recording every tier it tried. */
function clickLocator(fail: (a: Attempt) => string | null) {
  const log: Attempt[] = [];
  const run = async (a: Attempt) => {
    log.push(a);
    const message = fail(a);
    if (message) throw new Error(message);
  };
  const loc = {
    click: (o: { force?: boolean } = {}) => run({ kind: 'click', force: o.force }),
    dblclick: (o: { force?: boolean } = {}) => run({ kind: 'dblclick', force: o.force }),
    scrollIntoViewIfNeeded: () => run({ kind: 'scroll' }),
    first: () => ({ evaluate: () => run({ kind: 'evaluate' }) }),
  };
  return { loc, log };
}

describe('a click that an overlay intercepts', () => {
  const step: SkillStep = {
    tool: 'click',
    args: { target: '@e1' },
    locators: { target: [{ kind: 'testid', attr: 'data-testid', value: 'toggle-viz-picker' }] },
  };
  const source = emit(specOf([step]));
  const clickHelper = () => runnableHelpers(source).click as (loc: unknown, opts?: { dbl?: boolean }) => Promise<void>;

  it('inlines the click helper only when a step clicks', () => {
    expect(source).toContain('async function click(loc: Locator, opts: { dbl?: boolean } = {}): Promise<void> {');
    expect(source).toContain('const CLICK_TIER_MS = 5000;');
    const filled: SkillStep = { tool: 'fill', args: { target: '@e1', value: 'x' }, locators: { target: [{ kind: 'id', selector: '#i' }] } };
    expect(emit(specOf([filled]))).not.toContain('async function click');
  });

  it('inlines the fill helper only when a step fills, and mirrors reactSafeFill', () => {
    // The odoo sp4od failure: `locator.fill` fires only `input`, so a form
    // that commits on `change` never sees the value and the recorded effect
    // ("20% £ 36.00") never appears. The daemon has always executed a
    // recorded `fill` through reactSafeFill; the spec now says the same thing.
    const filled: SkillStep = { tool: 'fill', args: { target: '@e1', value: '3' }, locators: { target: [{ kind: 'id', selector: '#qty' }] } };
    const out = emit(specOf([filled]));
    expect(out).toContain("await fill(page.locator('#qty'), '3');");
    expect(out).toContain('async function fill(loc: Locator, value: string): Promise<void> {');
    // the same waits, the same order, the same events as daemon/inputs.ts
    expect(out).toContain("await loc.waitFor({ state: 'visible', timeout: FILL_WAIT_MS });");
    expect(out).toContain('const FILL_WAIT_MS = 10000;');
    expect(out).toContain('await loc.scrollIntoViewIfNeeded().catch(() => {});');
    expect(out).toContain("const setter = Object.getOwnPropertyDescriptor(proto, 'value')?.set;");
    expect(out).toContain("input.dispatchEvent(new Event('input', { bubbles: true }));");
    expect(out).toContain("input.dispatchEvent(new Event('change', { bubbles: true }));");
    // and the same fallback for a widget with no native value setter
    expect(out).toContain('    await loc.fill(value);');
    expect(syntaxErrors(out)).toEqual([]);
    // a flow that never fills carries none of it
    const clicked: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#go' }] } };
    expect(emit(specOf([clicked]))).not.toContain('async function fill');
  });

  it('inlines the select helper only when a step selects, and mirrors reactSafeSelect', () => {
    // fwat3 03-add: the app keyed the option by a per-record id, so a spec
    // that selected by the RECORDED value could only ever miss. The daemon
    // tries the visible label first and keeps the recorded value as the last
    // resort (`optionValue`); the spec now says the same thing.
    const selected: SkillStep = {
      tool: 'select',
      args: { target: '@e1', option: 'Client One', optionValue: '17' },
      locators: { target: [{ kind: 'id', selector: '#client' }] },
    };
    const out = emit(specOf([selected]));
    expect(out).toContain("await select(page.locator('#client'), 'Client One', '17');");
    expect(out).toContain('async function select(loc: Locator, label: string, fallbackValue?: string): Promise<void> {');
    // the same order as daemon/inputs.ts: look first, then the label wait, then value/index
    expect(out).toContain("if (opts.some((o) => o.label.trim() === v)) return 'label';");
    expect(out).toContain("if (opts.some((o) => o.value === v)) return 'value';");
    expect(out).toContain("if (f && opts.some((o) => o.value === f)) return 'fallback';");
    expect(out).toContain('  const result = await loc.selectOption({ label }).catch(() => null);');
    expect(out).toContain('  await loc.selectOption(label); // fall back to value/index matching');
    expect(syntaxErrors(out)).toEqual([]);
    // no recorded fallback value, no third argument
    const bare: SkillStep = { tool: 'select', args: { target: '@e1', option: 'Client One' }, locators: { target: [{ kind: 'id', selector: '#client' }] } };
    expect(emit(specOf([bare]))).toContain("await select(page.locator('#client'), 'Client One');");
    // a flow that never selects carries none of it
    const clicked: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#go' }] } };
    expect(emit(specOf([clicked]))).not.toContain('async function select');
  });

  it('inlines the hover helper only when a step hovers, and mirrors syntheticHover', () => {
    // A listbox that opens on `mouseenter` never sees Playwright's own hover
    // when the pointer was already inside the element: the daemon dispatches
    // the events at the element too, and so does the spec.
    const hovered: SkillStep = { tool: 'hover', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#menu' }] } };
    const out = emit(specOf([hovered]));
    expect(out).toContain("await hover(page.locator('#menu'));");
    expect(out).toContain('async function hover(loc: Locator): Promise<void> {');
    expect(out).toContain('  await loc.hover().catch(() => {});');
    expect(out).toContain("    for (const type of ['pointerover', 'mouseover', 'mouseenter', 'mousemove']) {");
    // mouseenter is the one that does not bubble
    expect(out).toContain("      el.dispatchEvent(new MouseEvent(type, { bubbles: type !== 'mouseenter' }));");
    expect(syntaxErrors(out)).toEqual([]);
    // a flow that never hovers carries none of it
    const clicked: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#go' }] } };
    expect(emit(specOf([clicked]))).not.toContain('async function hover');
  });

  it('bounds every tier so all of them fit inside one test timeout', () => {
    expect([...source.matchAll(/timeout: CLICK_TIER_MS/g)].length).toBeGreaterThanOrEqual(3);
    expect(4 * 5000).toBeLessThan(60_000);
  });

  it('takes tier 1 when a normal click lands', async () => {
    const { loc, log } = clickLocator(() => null);
    await clickHelper()(loc);
    expect(log).toEqual([{ kind: 'click', force: undefined }]);
  });

  it('forces past an overlay that intercepts pointer events (the grafana failure)', async () => {
    const { loc, log } = clickLocator((a) =>
      a.kind === 'click' && !a.force ? '<svg> from <div data-overlay-container> intercepts pointer events' : null,
    );
    await clickHelper()(loc);
    expect(log.map((a) => a.kind)).toEqual(['click', 'scroll', 'click']);
    expect(log[2]).toEqual({ kind: 'click', force: true });
  });

  it('dispatches a synthetic event when even a forced click cannot land', async () => {
    const { loc, log } = clickLocator((a) => (a.kind === 'evaluate' ? null : 'element is not visible'));
    await clickHelper()(loc);
    expect(log.map((a) => a.kind)).toEqual(['click', 'scroll', 'click', 'evaluate']);
  });

  it('reports the first failure when every tier loses', async () => {
    const { loc } = clickLocator(() => 'waiting for element to be visible, enabled and stable');
    await expect(clickHelper()(loc)).rejects.toThrow('waiting for element to be visible');
  });

  it('rethrows a strict-mode violation at once: no tier can fix two matches', async () => {
    const { loc, log } = clickLocator(() => 'strict mode violation: locator resolved to 3 elements');
    await expect(clickHelper()(loc)).rejects.toThrow('strict mode violation');
    expect(log.map((a) => a.kind)).toEqual(['click']);
  });

  it('doubles the click through the same tiers', async () => {
    const { loc, log } = clickLocator(() => null);
    await clickHelper()(loc, { dbl: true });
    expect(log).toEqual([{ kind: 'dblclick', force: undefined }]);
  });

  it('dispatches a right or modifier click plainly, as replay does', () => {
    const loc = { target: [{ kind: 'id' as const, selector: '#r' }] };
    const right = emit(specOf([{ tool: 'right_click', args: { target: '@e1' }, locators: loc }]));
    expect(right).toContain("await page.locator('#r').click({ button: 'right' });");
    expect(right).not.toContain('async function click');
    const mod = emit(specOf([{ tool: 'modifier_click', args: { target: '@e1', modifiers: ['Shift'] }, locators: loc }]));
    expect(mod).toContain("await page.locator('#r').click({ modifiers: ['Shift'] });");
  });
});

/**
 * A read is an OBSERVATION: replay skips one it cannot resolve and carries on
 * (runOneStep's isRead branch), because a value that could not be re-captured
 * says nothing about whether the procedure ran. The emitted spec has to make
 * the same distinction, or a grafana panel the verifier goes on to confirm
 * fails the whole flow.
 */
describe('a read never fails the flow', () => {
  const multi: SkillStep = {
    tool: 'read',
    args: { target: '@e1', what: 'text' },
    locators: { target: [{ kind: 'text', text: 'Notes for run sp3gra' }, { kind: 'css', selector: '.panel-content' }] },
    label: 'panel_content',
  };
  const source = emit(specOf([multi]));

  it('routes a multi-candidate read through readOptional, not a bare pick', () => {
    expect(source).toContain("outputs['01-do.panel_content'] = await readOptional(page, [");
    expect(source).toContain("], '01-do s_test1/1 target', async (loc: Locator) => (await loc.textContent()) ?? '');");
    // the pick is INSIDE the helper, so nothing at the call site can throw
    expect(source).not.toContain('= await pick(page, [');
    expect(source).toContain('async function readOptional(');
    expect(source).toContain('async function pick(page: Page');
    expect(syntaxErrors(source)).toEqual([]);
  });

  it('routes a single-candidate read the same way, so it cannot throw either', () => {
    const out = emit(
      specOf([{ tool: 'read', args: { target: '@e1', what: 'text' }, locators: { target: [{ kind: 'id', selector: '#total' }] }, label: 'total' }]),
    );
    expect(out).toContain("outputs['01-do.total'] = await readOptional(page, [\n      page.locator('#total'),\n    ], ");
    expect(out).not.toContain(".textContent()) ?? '';");
    expect(syntaxErrors(out)).toEqual([]);
  });

  it('leaves the value empty and says so when no candidate resolves', async () => {
    const warned: string[] = [];
    const { readOptional } = runnableHelpers(source, { warn: (line: string) => warned.push(line) });
    const value = await readOptional(
      pageStub(),
      [locatorStub(() => 0), locatorStub(() => 0)],
      '03-add s_e4d3e5/11 target',
      async () => 'never read',
    );
    expect(value).toBe('');
    expect(warned).toEqual(['[sitelooper skip] 03-add s_e4d3e5/11 target: read target not found — value left empty']);
  });

  it('swallows a failing read too, as replay does when the read itself errors', async () => {
    const warned: string[] = [];
    const { readOptional } = runnableHelpers(source, { warn: (line: string) => warned.push(line) });
    const value = await readOptional(pageStub(), [locatorStub(() => 1)], 'x y/1 target', async () => {
      throw new Error('element is not an <input>');
    });
    expect(value).toBe('');
    expect(warned).toHaveLength(1);
  });

  it('returns what the read read when the target is there', async () => {
    const { readOptional } = runnableHelpers(source);
    expect(await readOptional(pageStub(), [locatorStub(() => 1)], 'x y/1 target', async () => 'Notes for run sp3gra')).toBe(
      'Notes for run sp3gra',
    );
  });
});

/**
 * runOneStep settles the DOM BEFORE anything else it does — the
 * already-in-effect check included. Without it the odoo home-menu toggles ask
 * "is the popup showing?" of a menu that is still mid-close, skip the opening
 * click, and leave the `Sales` menuitem unreachable eight steps later.
 */
describe('every step settles first', () => {
  const click: SkillStep = { tool: 'click', args: { target: '@e1' }, locators: { target: [{ kind: 'id', selector: '#a' }] } };
  const source = emit(specOf([click, { ...click, locators: { target: [{ kind: 'id', selector: '#b' }] } }]));

  it('inlines settle once, with replay’s own constants', () => {
    expect(source.match(/async function settle\(page: Page\)/g)).toHaveLength(1);
    expect(source).toContain('const SETTLE_QUIET_MS = 250;');
    expect(source).toContain('const SETTLE_MAX_MS = 2000;');
    expect(source).toContain('const SETTLE_PROBE_MS = 60;');
    expect(source).toContain('observer.observe(document, { childList: true, subtree: true, attributes: true, characterData: true });');
    expect(syntaxErrors(source)).toEqual([]);
  });

  it('calls it at the top of every step', () => {
    expect(source.match(/await settle\(page\);/g)).toHaveLength(2);
  });

  it('settles ahead of the already-in-effect guard, not after it', () => {
    const opener: SkillStep = { ...click, expect: { addedContains: ['- menu "Apps"'] } };
    const lines = emit(specOf([opener])).split('\n').map((l) => l.trim());
    const settled = lines.indexOf('await settle(page);');
    const guard = lines.findIndex((l) => l.startsWith('if (await page.getByRole('));
    expect(settled).toBeGreaterThan(-1);
    expect(settled).toBeLessThan(guard);
  });

  it('settles again after a goto, before the assertions that gate it', () => {
    const goto: SkillStep = { tool: 'goto', args: { url: 'http://app.test/x' }, locators: {}, expect: { addedContains: ['- heading "Items"'] } };
    const lines = emit(specOf([goto])).split('\n').map((l) => l.trim());
    const nav = lines.indexOf("await page.goto('http://app.test/x');");
    expect(lines[nav + 1]).toBe('await settle(page);');
  });

  it('resolves on a page that answers evaluate', async () => {
    const { settle } = runnableHelpers(source);
    let seen: unknown;
    await settle({
      evaluate: async (_fn: unknown, arg: unknown) => {
        seen = arg;
      },
    });
    expect(seen).toEqual({ probe: 60, quiet: 250, max: 2000 });
  });

  it('swallows the error a navigating or detached page throws', async () => {
    const { settle } = runnableHelpers(source);
    await expect(
      settle({
        evaluate: async () => {
          throw new Error('Execution context was destroyed');
        },
      }),
    ).resolves.toBeUndefined();
  });
});
