import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { saveFlow, type Flow } from '../src/skills/flow.js';
import { SkillStore, type Skill } from '../src/skills/store.js';
import { compileFlow, exportFlowBundle, loadFlowBundle } from '../src/spec/index.js';

const dirs: string[] = [];
afterEach(() => {
  for (const dir of dirs.splice(0)) fs.rmSync(dir, { recursive: true, force: true });
});

function temp(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sl-bundle-'));
  dirs.push(dir);
  return dir;
}

function fixtures(dir: string): { flowFile: string; store: SkillStore } {
  const store = new SkillStore(path.join(dir, 'skills'));
  const skill: Skill = {
    id: 's_portable',
    origin: 'http://localhost:4173',
    template: 'open projects',
    params: {},
    preconditions: { urlPattern: 'http://localhost:4173/' },
    steps: [{ tool: 'goto', args: { url: 'http://localhost:4173/projects' }, locators: {} }],
    stats: { uses: 2, successes: 2, partial: 0, created: '2026-09-07T00:00:00.000Z', failedAtStep: {}, fallthroughs: 0 },
    status: 'validated',
    provenance: { session: 'author', instruction: 'open projects', created: '2026-09-07T00:00:00.000Z' },
  };
  store.put(skill);
  const flow: Flow = {
    name: 'portable',
    origin: skill.origin,
    startUrl: `${skill.origin}/`,
    vars: [],
    steps: [{ id: '01-open', instruction: 'open projects', skill: skill.id, outputs: [], recorded: {} }],
    provenance: { session: 'author', created: '2026-09-07T00:00:00.000Z' },
  };
  return { flowFile: saveFlow(flow, path.join(dir, 'portable.json')), store };
}

describe('portable procedure snapshots', () => {
  it('exports compiler provenance and compiles without the user-level store', () => {
    const dir = temp();
    const { flowFile, store } = fixtures(dir);
    const bundleFile = path.join(dir, 'project', 'procedures.json');
    const exported = exportFlowBundle(flowFile, { outFile: bundleFile, store, now: '2026-09-07T12:00:00.000Z' });
    expect(exported.missingSkills).toEqual([]);
    expect(exported.bundle.compiler.name).toBe('sitelooper');
    expect(exported.bundle.compiler.version).toMatch(/^\d+\.\d+\.\d+$/);
    expect(loadFlowBundle(bundleFile).skills.map((skill) => skill.id)).toEqual(['s_portable']);

    const result = compileFlow(bundleFile, { outDir: path.join(dir, 'generated') });
    expect(result.compilable).toBe(true);
    expect(result.diagnostics).toEqual([]);
    expect(fs.readFileSync(result.flowFile!, 'utf8')).toContain(`Generated by sitelooper ${result.compiler.version}`);
  });

  it('reports missing pins in the exported snapshot', () => {
    const dir = temp();
    const { flowFile } = fixtures(dir);
    const exported = exportFlowBundle(flowFile, { outFile: path.join(dir, 'procedures.json'), store: new SkillStore(path.join(dir, 'empty')) });
    expect(exported.missingSkills).toEqual(['s_portable']);
  });

  it('keeps diagnostic permission separate from overwriting the scaffold', () => {
    const dir = temp();
    const { flowFile, store } = fixtures(dir);
    const skill = store.get('s_portable')!;
    skill.status = 'demoted';
    store.put(skill);
    const out = path.join(dir, 'out');

    expect(compileFlow(flowFile, { store, outDir: out, overwriteSpec: true }).refused).toBe(true);
    const first = compileFlow(flowFile, { store, outDir: out, allowDemoted: true });
    fs.appendFileSync(first.specFile!, '\n// user assertion\n');
    const again = compileFlow(flowFile, { store, outDir: out, allowDemoted: true });
    expect(again.specFile).toBeNull();
    expect(fs.readFileSync(path.join(out, 'portable.spec.ts'), 'utf8')).toContain('// user assertion');
  });

  it('does not call an emitted TODO ready to execute', () => {
    const dir = temp();
    const { flowFile, store } = fixtures(dir);
    const skill = store.get('s_portable')!;
    skill.steps = [{ tool: 'future_browser_action', args: {}, locators: {} }];
    store.put(skill);
    const result = compileFlow(flowFile, { store, outDir: path.join(dir, 'out') });
    expect(result.compilable).toBe(false);
    expect(result.compileBlockers.join('\n')).toContain('TODO:');
  });
});
